"""initial

Revision ID: 43aa1eb27eb9
Revises: 1b81de3e442f
Create Date: 2025-12-01 17:21:22.458841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43aa1eb27eb9'
down_revision = '1b81de3e442f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stress_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('hr', sa.Float(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('eda', sa.Float(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('history_stress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_stress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('hr', sa.FLOAT(), nullable=True),
    sa.Column('temp', sa.FLOAT(), nullable=True),
    sa.Column('eda', sa.FLOAT(), nullable=True),
    sa.Column('label', sa.VARCHAR(length=128), nullable=True),
    sa.Column('confidence_level', sa.FLOAT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stress_history')
    # ### end Alembic commands ###
